version: '3'

services:
  # Tenki forecast reverse proxy
  traefik-reverse-proxy:
    build: ./reverse-proxy
    container_name: traefik-reverse-proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --api --docker
    # restart: always


  # Tenki forecast client
  tenki-forecast-client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GMAPS_API_KEY=AIzaSyA53AqsfawEZBHOUi2UjHfKvgi37tl7cXA
      - TENKI_FORECAST_SERVER_API_URL=http://localhost:4040/api/tenki-forecast
    labels:
      - traefik.frontend.rule=Path:/
      # @see https://docs.traefik.io/basics/#priorities
      - traefik.frontend.priority=10
    # restart: always


  # Tenki forecast server
  server:
    build: ./server
    ports:
      - 4040:4040
    environment:
      - NODE_ENV=development
      - PORT=4040
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    labels:
      - traefik.frontend.rule=PathPrefix:/api
      # @see https://docs.traefik.io/basics/#priorities
      - traefik.frontend.priority=20
    # restart: always
