version: '3'

services:
  # Tenki forecast reverse proxy
  traefik-reverse-proxy:
    build: ./reverse-proxy
    container_name: traefik-reverse-proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --api --docker
    restart: always


  # Tenki forecast server
  server:
    build: ./server
    ports:
      - 4040:4040
    environment:
      - NODE_ENV=development
      - PORT=4040
      - REDIS_HOST=redis://127.0.0.1:6379
      - REDIS_PORT=6379
    restart: always
